### ISSUE TITLE
Accessing SPIRType member properties 

### ISSUE THREAD

**Issue by Hugobros3** [scenerygraphics/spirvcrossj#10]
Hello

I am working on a brand new renderer for my project, and I need to do some preprocessing on my GLSL shader code before handing it over to either Vulkan or OpenGL 4.0. 

My problem with those bindings is that there doesn't appear to be any mapped functionality from the original `SPIRType` struct, the best I can get is a SWIGTYPE_p_SPIRType object from Compiler.getType, but as far as I can understand it's just an object wrapping a pointer, with no field access

Because I need to inspect the shader stages uniforms to build my descriptor set layouts, I am kind of stuck on this, and I'm not that familiar with SWIG or C++ in general really, so I'd really appreciate any pointers or help for a fix.

**Comment by skalarproduktraum** [comment]
Hi Hugo,

this issue is actually something I am looking at at the moment, for exactly the same reason 🤣 
As my SWIG-fu is at an end on how to include with SPIRType defs, I'll ask the SWIG people and get back to this issue ASAP.

cheers, and thanks for your interest in the project! 👍

**Comment by skalarproduktraum** [comment]
Okay, so the SWIG problem turned out to be just a missing include... this lead however to a few more issues, so I'm updating the whole project now, also to be in sync with the Vulkan SDK releases. Stay tuned.

**Comment by Hugobros3** [comment]
Very nice ! Thank you.

**Comment by skalarproduktraum** [comment]
Hello again,

#11 is merged now, addressing the issues you raised here. 
The CIs are producing new artifacts, which should be up on Maven central within about one hour. Use version `0.5.0-1.1.85-SNAPSHOT` (you can keep an eye on https://oss.sonatype.org/content/repositories/public/graphics/scenery/spirvcrossj/ for the new version to appear). I'll perform some more testing and then release a final version in the next days.

I'll close this issue for now, if you feel not everything has been addressed or there's something to add, please reopen :+1: :)

**Comment by skalarproduktraum** [comment]
@Hugobros3, just as a little heads-up, 0.5.0-1.1.85 is now released :+1:

**Comment by Hugobros3** [comment]
Thanks I'll have a check. I've tried to use the snapshot versions a while ago but gradle was having trouble pulling the jars apparently.

**Comment by skalarproduktraum** [comment]
Oh, that shouldn't happen. Let me know if that is still the case, please :)
