### ISSUE TITLE
The compiled jar contains two copies of the module

### ISSUE THREAD

**Issue by EmmiaSilk** [scenerygraphics/spirvcrossj#12]
All of the classes are contained twice in the jar, both in the package `graphics.scenery.spirvcrossj` and in `main.java.graphics.scenery.spirvcrossj`.

**Comment by skalarproduktraum** [comment]
Hi @EmmiaSilk,

thanks for the report. I just tried to verify this, but what's contained in the JAR is not two copies of the same classes (which the Maven enforcer would complain about), but in `graphics.scenery.spirvcrossj` the compiled `.class` files, and in `main.java.graphics.scenery.spirvcrossj` the Java source files.

The latter ones should not be there, but the separate sources JAR (e.g. https://oss.sonatype.org/content/groups/public/graphics/scenery/spirvcrossj/0.5.0-1.1.85/spirvcrossj-0.5.0-1.1.85-sources.jar). Here we come to the actual issue though -- the sources JAR actually contains two copies of the source _and_ also a binary. I'll fix this soon.

**Comment by skalarproduktraum** [comment]
Okay, this has been fixed. A new SNAPSHOT version should be up soon 👍
