### ISSUE TITLE
classloader hack is more general than imagej-launcher

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/spirvcrossj#8]
https://github.com/scenerygraphics/spirvcrossj/blob/270bc5efea2dfcad68f7ce6e31b41b5fd006767f/src/main/java/graphics/scenery/spirvcrossj/Loader.java#L98

I ran into this issue when dynamically loading sciview + deps.

The hilarious workaround to take advantage of this workaround is:
```
(java.lang.System/setProperty "java.class.path" (str "imagej-launcher"
                                                     (java.lang.System/getProperty "path.separator")
                                                     (java.lang.System/getProperty "java.class.path")))
```

Perhaps it would be possible to check an extra system property like "spirvcrossjUseContextClassloader," because the above workaround is a little bit out there.

**Comment by skalarproduktraum** [comment]
The above commit implements your suggestion, @kephale. Set `spirvcrossj.useContextClassLoader`, and it'll have the same effect as having the imagej-launcher on the class path.

Thanks for the suggestion!
